UPLOAD_FOLDER = 'storage/uploads'
OUTPUT_FOLDER = 'storage/outputs'
SQLITE_DB = 'jobs.db'
SCHEMA_PATH = 'schema.sql'
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'