
services:
  unoserver:
    image: libreofficedocker/libreoffice-unoserver:3.18
    container_name: unoserver
    ports:
      - 2004:2004  # unoconv API exposed on port 2004
    environment:
      - DISPLAY=:99
    volumes:
          - ./storage/uploads:/storage/uploads
          - ./storage/outputs:/storage/outputs